version: '3.8'

services:
  # Broker MQTT
  broker:
    image: eclipse-mosquitto:2.0
    container_name: broker_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - rede_recarga

  empresa_001:
    build:
      context: ./empresa
      dockerfile: Dockerfile
    container_name: empresa_001
    environment:
      - EMPRESA_ID=001
    ports:
      - "8001:8001"
    volumes:
      - ./empresa/data:/app/data
    networks:
      - rede_recarga
    depends_on:
      - broker

  empresa_002:
    build:
      context: ./empresa
      dockerfile: Dockerfile
    container_name: empresa_002
    environment:
      - EMPRESA_ID=002
    ports:
      - "8002:8002"
    volumes:
      - ./empresa/data:/app/data
    networks:
      - rede_recarga
    depends_on:
      - broker

  empresa_003:
    build:
      context: ./empresa
      dockerfile: Dockerfile
    container_name: empresa_003
    environment:
      - EMPRESA_ID=003
    ports:
      - "8003:8003"
    volumes:
      - ./empresa/data:/app/data
    networks:
      - rede_recarga
    depends_on:
      - broker

  veiculo:
    build:
      context: ./veiculo
      dockerfile: Dockerfile
    container_name: veiculo
    stdin_open: true
    tty: true
    volumes:
      - ./empresa/data:/app/data
    networks:
      - rede_recarga
    depends_on:
      - broker
      - empresa_001
      - empresa_002
      - empresa_003

networks:
  rede_recarga:
    driver: bridge